version: '3'
services:
  nginx:
    image: nginx-server
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
  mariadb:
    image: mariadb-image
    build: ./requirements/mariadb
    restart: always

#volumes:
#  containers:
#    my-sql-volume: