version: '3'
services:
  nginx:
    image: nginx-server
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
  mariadb:
    image: mariadb-image
    build: ./requirements/mariadb
    volumes :
      - my-sql-volume:/var/lib/mysql
    restart: always

volumes:
  my-sql-volume: