version: '3'
services:
  nginx:
    image: nginx-server
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - web-data:/var/www/
    restart: always
  mariadb:
    image: mariadb-image
    build:
      context: ./requirements/mariadb
    secrets:
      - my-sql-credentials   
    volumes:
      - db-data:/var/lib/mysql
    restart: always

secrets:
  my-sql-credentials:
    file: ../secrets/.env

volumes:
  db-data:
    driver: local
  web-data:
    driver: local