version: '3'
services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-data:/var/www/html/:rw
    secrets:
      - my-credentials
    restart: always

  mariadb:
    image: mariadb
    container_name : mariadbContainer
    build:
      context: ./requirements/mariadb
    secrets:
      - my-credentials
    volumes:
      - db-data:/var/lib/mysql/:rw
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    secrets:
      - my-credentials
    volumes:
      - wp-data:/var/www/html/:rw
    restart: always

secrets:
  my-credentials:
    file: ../secrets/.env

networks:
  inception:
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: "~/data/db-data/"
      o: bind
  wp-data:
    driver: local
    driver_opts:
      type: none
      device: "~/data/wp-data/"
      o: bind